apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-server
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      # nodePort: 30000

--- 
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-container
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      # nodePort: 30001