apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              subPath: "mysql"
              name: mysql-data
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
              # valueFrom:
              #   secretKeyRef:
              #     name: mysql-secrets
              #     key: ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: oxzionapi
          resources:
            requests:
              cpu: 500m
            limits:
              cpu: 500m
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-disk